// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarStore.Models
{
    public partial class Car
    {
        public int Id { get; set; }
        public string Model { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public long Mileage { get; set; }
        public int Year { get; set; }
        public string Brand { get; set; }
        public string ImageUrl { get; set; }
        public int CarTypeId { get; set; }
        public int FuelTypeId { get; set; }

        public virtual CarType CarType { get; set; }
        public virtual FuelType FuelType { get; set; }
    }
}