// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarStore.Models
{
    public partial class ShoppingCartItem
    {
        public int Id { get; set; }
        public int CarId { get; set; }
        public string Quantity { get; set; }
        public Guid ShoppingCartId { get; set; }

        public virtual Car Car { get; set; }
    }
}